export enum ROLES {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  MOTORIZED = 'MOTORIZED',
  RECEPTIONIST = 'RECEPTIONIST',
}

export enum STATES {
  REGISTERED = 'REGISTRADO',
  PICKUP = 'RECOGIDO',
  IN_WHAREHOUSE = 'EN ALMACEN',
  IN_TRANSIT = 'EN TRANSITO',
  DELIVERED = 'ENTREGADO',
  CANCELED = 'CANCELADO',
  REJECTED  = 'RECHAZADO',
  RESCHEDULED = 'REPROGRAMADO',
}

export enum ACCESS_LEVEL {
  DEVELOPER = 30,
  MANTEINER = 40,
  OWNER = 50,
}
