export enum ROLES {
  ADMINISTRADOR = 'ADMINISTRADOR',
  EMPRESA = 'EMPRESA',
  MOTORIZADO = 'MOTORIZADO',
  RECEPCIONISTA = 'RECEPCIONISTA',
  EMPRESA_DISTRIBUIDOR = 'EMPRESA_DISTRIBUIDOR',
}

export enum STATES {
  REGISTERED = 'REGISTRADO',
  PICKUP = 'RECOGIDO',
  IN_WHAREHOUSE = 'EN ALMACEN',
  IN_TRANSIT = 'EN TRANSITO',
  DELIVERED = 'ENTREGADO',
  CANCELED = 'CANCELADO',
  ANNULLED = 'ANULADO',
  REJECTED = 'RECHAZADO EN PUNTO',
  RESCHEDULED = 'REPROGRAMADO',
}

export enum ACCESS_LEVEL {
  DEVELOPER = 30,
  MANTEINER = 40,
  OWNER = 50,
}
